server:
  port: 8081
  servlet:
    context-path: /CRUD

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/demospringboot"
    username: root
    password: 16092004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false